//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNClientUsername) DeepCopyInto(out *VPNClientUsername) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNClientUsername.
func (in *VPNClientUsername) DeepCopy() *VPNClientUsername {
	if in == nil {
		return nil
	}
	out := new(VPNClientUsername)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPNClientUsername) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNClientUsernameInitParameters) DeepCopyInto(out *VPNClientUsernameInitParameters) {
	*out = *in
	if in.ACLProfileName != nil {
		in, out := &in.ACLProfileName, &out.ACLProfileName
		*out = new(string)
		**out = **in
	}
	if in.ClientProfileName != nil {
		in, out := &in.ClientProfileName, &out.ClientProfileName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.GuaranteedEndpointPermissionOverrideEnabled != nil {
		in, out := &in.GuaranteedEndpointPermissionOverrideEnabled, &out.GuaranteedEndpointPermissionOverrideEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SubscriptionManagerEnabled != nil {
		in, out := &in.SubscriptionManagerEnabled, &out.SubscriptionManagerEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNClientUsernameInitParameters.
func (in *VPNClientUsernameInitParameters) DeepCopy() *VPNClientUsernameInitParameters {
	if in == nil {
		return nil
	}
	out := new(VPNClientUsernameInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNClientUsernameList) DeepCopyInto(out *VPNClientUsernameList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VPNClientUsername, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNClientUsernameList.
func (in *VPNClientUsernameList) DeepCopy() *VPNClientUsernameList {
	if in == nil {
		return nil
	}
	out := new(VPNClientUsernameList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPNClientUsernameList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNClientUsernameObservation) DeepCopyInto(out *VPNClientUsernameObservation) {
	*out = *in
	if in.ACLProfileName != nil {
		in, out := &in.ACLProfileName, &out.ACLProfileName
		*out = new(string)
		**out = **in
	}
	if in.ClientProfileName != nil {
		in, out := &in.ClientProfileName, &out.ClientProfileName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.GuaranteedEndpointPermissionOverrideEnabled != nil {
		in, out := &in.GuaranteedEndpointPermissionOverrideEnabled, &out.GuaranteedEndpointPermissionOverrideEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MsgVPNName != nil {
		in, out := &in.MsgVPNName, &out.MsgVPNName
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionManagerEnabled != nil {
		in, out := &in.SubscriptionManagerEnabled, &out.SubscriptionManagerEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNClientUsernameObservation.
func (in *VPNClientUsernameObservation) DeepCopy() *VPNClientUsernameObservation {
	if in == nil {
		return nil
	}
	out := new(VPNClientUsernameObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNClientUsernameParameters) DeepCopyInto(out *VPNClientUsernameParameters) {
	*out = *in
	if in.ACLProfileName != nil {
		in, out := &in.ACLProfileName, &out.ACLProfileName
		*out = new(string)
		**out = **in
	}
	if in.ClientProfileName != nil {
		in, out := &in.ClientProfileName, &out.ClientProfileName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.GuaranteedEndpointPermissionOverrideEnabled != nil {
		in, out := &in.GuaranteedEndpointPermissionOverrideEnabled, &out.GuaranteedEndpointPermissionOverrideEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MsgVPNName != nil {
		in, out := &in.MsgVPNName, &out.MsgVPNName
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.SubscriptionManagerEnabled != nil {
		in, out := &in.SubscriptionManagerEnabled, &out.SubscriptionManagerEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNClientUsernameParameters.
func (in *VPNClientUsernameParameters) DeepCopy() *VPNClientUsernameParameters {
	if in == nil {
		return nil
	}
	out := new(VPNClientUsernameParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNClientUsernameSpec) DeepCopyInto(out *VPNClientUsernameSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNClientUsernameSpec.
func (in *VPNClientUsernameSpec) DeepCopy() *VPNClientUsernameSpec {
	if in == nil {
		return nil
	}
	out := new(VPNClientUsernameSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPNClientUsernameStatus) DeepCopyInto(out *VPNClientUsernameStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPNClientUsernameStatus.
func (in *VPNClientUsernameStatus) DeepCopy() *VPNClientUsernameStatus {
	if in == nil {
		return nil
	}
	out := new(VPNClientUsernameStatus)
	in.DeepCopyInto(out)
	return out
}
