// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type VPNClientUsernameInitParameters struct {

	// The ACL Profile of the Client Username. Modifying this attribute while the object (or the relevant part of the object) is administratively enabled may be service impacting as enabled will be temporarily set to false to apply the change. Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `"default"`.
	ACLProfileName *string `json:"aclProfileName,omitempty" tf:"acl_profile_name,omitempty"`

	// The Client Profile of the Client Username. Modifying this attribute while the object (or the relevant part of the object) is administratively enabled may be service impacting as enabled will be temporarily set to false to apply the change. Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `"default"`.
	ClientProfileName *string `json:"clientProfileName,omitempty" tf:"client_profile_name,omitempty"`

	// Enable or disable the Client Username. When disabled, all clients currently connected as the Client Username are disconnected. Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `false`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Enable or disable guaranteed endpoint permission override for the Client Username. When enabled all guaranteed endpoints may be accessed, modified or deleted with the same permission as the owner. Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `false`.
	GuaranteedEndpointPermissionOverrideEnabled *bool `json:"guaranteedEndpointPermissionOverrideEnabled,omitempty" tf:"guaranteed_endpoint_permission_override_enabled,omitempty"`

	// Enable or disable the subscription management capability of the Client Username. This is the ability to manage subscriptions on behalf of other Client Usernames. Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `false`.
	SubscriptionManagerEnabled *bool `json:"subscriptionManagerEnabled,omitempty" tf:"subscription_manager_enabled,omitempty"`
}

type VPNClientUsernameObservation struct {

	// The ACL Profile of the Client Username. Modifying this attribute while the object (or the relevant part of the object) is administratively enabled may be service impacting as enabled will be temporarily set to false to apply the change. Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `"default"`.
	ACLProfileName *string `json:"aclProfileName,omitempty" tf:"acl_profile_name,omitempty"`

	// The Client Profile of the Client Username. Modifying this attribute while the object (or the relevant part of the object) is administratively enabled may be service impacting as enabled will be temporarily set to false to apply the change. Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `"default"`.
	ClientProfileName *string `json:"clientProfileName,omitempty" tf:"client_profile_name,omitempty"`

	// Enable or disable the Client Username. When disabled, all clients currently connected as the Client Username are disconnected. Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `false`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Enable or disable guaranteed endpoint permission override for the Client Username. When enabled all guaranteed endpoints may be accessed, modified or deleted with the same permission as the owner. Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `false`.
	GuaranteedEndpointPermissionOverrideEnabled *bool `json:"guaranteedEndpointPermissionOverrideEnabled,omitempty" tf:"guaranteed_endpoint_permission_override_enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the Message VPN.
	MsgVPNName *string `json:"msgVpnName,omitempty" tf:"msg_vpn_name,omitempty"`

	// Enable or disable the subscription management capability of the Client Username. This is the ability to manage subscriptions on behalf of other Client Usernames. Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `false`.
	SubscriptionManagerEnabled *bool `json:"subscriptionManagerEnabled,omitempty" tf:"subscription_manager_enabled,omitempty"`
}

type VPNClientUsernameParameters struct {

	// The ACL Profile of the Client Username. Modifying this attribute while the object (or the relevant part of the object) is administratively enabled may be service impacting as enabled will be temporarily set to false to apply the change. Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `"default"`.
	// +kubebuilder:validation:Optional
	ACLProfileName *string `json:"aclProfileName,omitempty" tf:"acl_profile_name,omitempty"`

	// The Client Profile of the Client Username. Modifying this attribute while the object (or the relevant part of the object) is administratively enabled may be service impacting as enabled will be temporarily set to false to apply the change. Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `"default"`.
	// +kubebuilder:validation:Optional
	ClientProfileName *string `json:"clientProfileName,omitempty" tf:"client_profile_name,omitempty"`

	// Enable or disable the Client Username. When disabled, all clients currently connected as the Client Username are disconnected. Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `false`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Enable or disable guaranteed endpoint permission override for the Client Username. When enabled all guaranteed endpoints may be accessed, modified or deleted with the same permission as the owner. Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `false`.
	// +kubebuilder:validation:Optional
	GuaranteedEndpointPermissionOverrideEnabled *bool `json:"guaranteedEndpointPermissionOverrideEnabled,omitempty" tf:"guaranteed_endpoint_permission_override_enabled,omitempty"`

	// The name of the Message VPN.
	// +kubebuilder:validation:Required
	MsgVPNName *string `json:"msgVpnName" tf:"msg_vpn_name,omitempty"`

	// The password for the Client Username. This attribute is absent from a GET and not updated when absent in a PUT, subject to the exceptions in note 4 (refer to the `Notes` section in the SEMP API `Config reference`). Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `""`.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// Enable or disable the subscription management capability of the Client Username. This is the ability to manage subscriptions on behalf of other Client Usernames. Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `false`.
	// +kubebuilder:validation:Optional
	SubscriptionManagerEnabled *bool `json:"subscriptionManagerEnabled,omitempty" tf:"subscription_manager_enabled,omitempty"`
}

// VPNClientUsernameSpec defines the desired state of VPNClientUsername
type VPNClientUsernameSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VPNClientUsernameParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VPNClientUsernameInitParameters `json:"initProvider,omitempty"`
}

// VPNClientUsernameStatus defines the observed state of VPNClientUsername.
type VPNClientUsernameStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VPNClientUsernameObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// VPNClientUsername is the Schema for the VPNClientUsernames API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,solacebroker}
type VPNClientUsername struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              VPNClientUsernameSpec   `json:"spec"`
	Status            VPNClientUsernameStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VPNClientUsernameList contains a list of VPNClientUsernames
type VPNClientUsernameList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VPNClientUsername `json:"items"`
}

// Repository type metadata.
var (
	VPNClientUsername_Kind             = "VPNClientUsername"
	VPNClientUsername_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VPNClientUsername_Kind}.String()
	VPNClientUsername_KindAPIVersion   = VPNClientUsername_Kind + "." + CRDGroupVersion.String()
	VPNClientUsername_GroupVersionKind = CRDGroupVersion.WithKind(VPNClientUsername_Kind)
)

func init() {
	SchemeBuilder.Register(&VPNClientUsername{}, &VPNClientUsernameList{})
}
